# Generated by Django 3.0.8 on 2020-07-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management_app', '0002_authormodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='author',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='author',
            field=models.ManyToManyField(to='library_management_app.AuthorModel'),
        ),
    ]
