# Generated by Django 3.0.8 on 2020-07-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management_app', '0004_auto_20200714_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='author',
            field=models.ManyToManyField(related_name='books', to='library_management_app.AuthorModel'),
        ),
    ]
