# Generated by Django 3.0.8 on 2020-07-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management_app', '0005_auto_20200714_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
