# Generated by Django 3.0.8 on 2020-07-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management_app', '0010_remove_bookmodel_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='cover',
            field=models.ImageField(blank=True, default='book3.jpg', null=True, upload_to=''),
        ),
    ]
